spring:
  application:
    name: flight-service
  datasource:
#    url: jdbc:mysql://mysql-db:3306/flight_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://${DB_HOST:localhost}:3306/travelnest_flights?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:Chamod}
    password: ${DB_PASSWORD:Chamod#100}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnf5DQsiaKhxVj+i2OROx
    jZuSJ9wZrd0EInhIXY0KWri9mLGbTsHolNLFKtQVExTrnxwyd/1qB1/lH1mpE4EI
    DA+xddXJ/KQg/OrrfRTnEqe+EoeI2pv8YNhB/gcqYw7Z3C8sAS0KMDTUShOiuqcH
    Lu57AiQyHmOdcvWXuDxCsycCA3tjn1ftOX3plOis2q4w2eBq7Jq1nRYmlR9+Ztrq
    vv1vcjY5gQyPXV3KWETf8c2HCLwN87nY3anmJDfuFlXMttHleCbH17TmlVbuVKPM
    V9lfP5OKrUtqtLhbN/v6GWLf6su2cDioKkDJ4DPRTP0PC8ir3dXB1YG1rW8hOur5
    GwIDAQAB
    -----END PUBLIC KEY-----
