apiVersion: v1
kind: ConfigMap
metadata:
  name: travelnest-config
  namespace: travelnest
data:
  EUREKA_URI: "http://service-registry:8761/eureka"
  RABBITMQ_HOST: "rabbitmq-service" # Replace with actual if external
  RABBITMQ_PORT: "5672"
