apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: travelnest
type: Opaque
data:
  # Replace values with base64 encoded real keys
  JWT_PRIVATE_KEY: "dGhpcy1pcy1hLXBsYWNlaG9sZGVy"
  JWT_PUBLIC_KEY: "dGhpcy1pcy1hLXBsYWNlaG9sZGVy"
