apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: travelnest
type: Opaque
data:
  # Replace values with base64 encoded real values
  RABBITMQ_USERNAME: "Z3Vlc3Q="
  RABBITMQ_PASSWORD: "Z3Vlc3Q="
