---
- hosts: jenkins
  tags: [k8s]
  tasks:
    - name: Apply namespace
      command: kubectl apply -f ../k8s/namespace.yaml
    - name: Apply secrets config
      command: kubectl apply -f ../k8s/db-secret.yaml
