spring:
  application:
    name: user-service
  datasource:
#    url: jdbc:mysql://mysql-db:3306/account_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/travelnest_users?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Chamod@100
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCd/kNCyJoqHFWP
    6LY5E7GNm5In3Bmt3QQieEhdjQpauL2YsZtOweiU0sUq1BUTFOufHDJ3/WoHX+Uf
    WakTgQgMD7F11cn8pCD86ut9FOcSp74Sh4jam/xg2EH+BypjDtncLywBLQowNNRK
    E6K6pwcu7nsCJDIeY51y9Ze4PEKzJwIDe2OfV+05femU6KzarjDZ4GrsmrWdFiaV
    H35m2uq+/W9yNjmBDI9dXcpYRN/xzYcIvA3zudjdqeYkN+4WVcy20eV4JsfXtOaV
    Vu5Uo8xX2V8/k4qtS2q0uFs3+/oZYt/qy7ZwOKgqQMngM9FM/Q8LyKvd1cHVgbWt
    byE66vkbAgMBAAECggEAGKeb8WkCfb3MMFfdT8zd8T4ssaGsNDCAO6zPhiHDUuLv
    W0uj88dYtxipAgT0gPTLzBmHWqgmCp6RT7IbK1sAWXl9dOj2y0EFkNJMC0newU+B
    3rxdw9eBq88zhSOzHqArqSuHT2uq4ljsI98qjrwP5+f5NB1X4NwkrtLaaTqmIfSe
    kHJ/b4H4XLjGfScEtFcChqddXDOtrNU818IVQ1flL09Aey+aZPb0eX92Z8ZjphBV
    sg3JOKdmPr1Jh0n/QYad28EXd9jlMjkQxVWe5c5sbn5WFduJDCKFFtLIemhX3gyd
    KqEdvVnvLuj3G0aweIWqghc8rZkCaWwQIz9lLhjLOQKBgQDBjYXOIPqKBWlY20UV
    afm8fDnKtFi7LeymVHguKsPSb0sKBtGazXc3O+692TLy+hGLWLc+4DukQ6ZYMVmr
    1H2jT2GJPu8Zp6FGT95LcOE39L+BELZEOzgU0aaPT31kggqDhbuqqalMJewQE9zP
    l/5entwm2OHsYK6ppTJ1579u3QKBgQDQ97KNQg2W5tqWIkJYwHAyPYNH1+jRccSB
    gRZULdfZ+iCXXzm52MWYM1utOC9nCU6Zra3EOfOILeNoL7URYdAqvxn4Ur2mP/C0
    9m+k4aylVfCtF0TVgq6zv2CdMbEd2rf6FsGWUJfoLHpsWAW1tIp3Qk0ZFiHRI9wY
    MJmTlRq8VwKBgHvi9e5GNZb6d7+kOcfHGU6HxQX2AYVtk7ezAWmrfcPH8KPuUWNg
    eBomhl2GFJJpdalXk5LvO72cf3CbxeWyEOji+m86lRg6r4Otw39ONRn30kvuQnvR
    28eXmaDJJF2cztX4V3KZPf+7limETSWjB/HQhOFomNMP3zw+vNmzCFkRAoGAFXmP
    GOMz4FEjH5Cvvs0v+onFxwlSPMvzRNfOQqJfb2A8HzJDDW1QiR6mCjwe6vjS4gou
    NF88Pr9wglF8yyeBLBNtiM5//OjPRNmaiZhDlM4rKK6efU6rw38kX6Mur4G9rG7Q
    QDFSGyMPBblaBN1j6XOf1rcmjIah5L6B2d/V2osCgYEAsWqrisbetnTicHge+8T7
    VDNnYKOvGugImiVSNVJERdnT8/B/k8sgKVOITVxsTx6EAGvWbTegx30YKPT43EuO
    kIswsNf6sXSO2cR8DgsQOo7kSJqdSVG0Rcpkc+FgAg5L33vaZ9eg3xxpJQFUhcqZ
    Ks704tg6GPaDJP3zs9eFdwk=
    -----END PRIVATE KEY-----
